### ISSUE TITLE
Get Graphics for WordPress Display

### ISSUE THREAD

**Issue by darkwing** [mozilla/wp-offline-shell#77]
Need Harald's graphic genius for awesome WordPress listing icons.

**Comment by digitarald** [comment]
https://www.dropbox.com/s/6mkjzfc99rue3ng/wp-offline-shell.zip?dl=0

Preview: ![Preview](https://photos-6.dropbox.com/t/2/AADTJbolYoRiSNrbF-OTefIddyHNeMShew4HjDQdxaDNXQ/12/1864007/png/32x32/1/_/1/2/Offline%20Shell%20Icon%402x.png/ELXYvwEY1uf9RiACKAI/jpgw75zFFMyQ5t65cu8VHJ_SR8PVOoQ_nH2olgQgUu0?size=1280x960&size_mode=3)

**Comment by darkwing** [comment]
Completed last week.
