### ISSUE TITLE
commit composer.lock to repo

### ISSUE THREAD

**Issue by mykmelez** [mozilla/wp-offline-shell#98]
Per https://circleci.com/docs/composer-api-rate-limit, we should commit the composer.lock file to the repo, so Composer knows exactly which versions of dependencies to install/update, and so it doesn't hit the GitHub API as often.

**Comment by mykmelez** [comment]
`composer update --prefer-source --no-interaction` would also help.

**Comment by staabm** [comment]
prefer-source is no longer the way to go. a few weeks ago composer and github api changed in a way that it wont trigger the api rate limit.

see https://twitter.com/seldaek/status/708236348281495552

**Comment by marco-c** [comment]
Oh, thanks for the heads-up! I'll switch to `--prefer-dist` everywhere.

**Comment by staabm** [comment]
IIRC --prefer-dist is the default on travis, so you dont need to pass the arg.

**Comment by mykmelez** [comment]
> IIRC --prefer-dist is the default on travis, so you dont need to pass the arg.

In this case, I'm building a Docker image with this plugin pre-installed (along with two others that also use Composer) over in https://github.com/mykmelez/wordpress-pwa, and the image gets rebuilt by Docker Hub, so unless Docker Hub also sets --prefer-dist as the default, it'll still be handy to set it explicitly.

**Comment by marco-c** [comment]
> In this case, I'm building a Docker image with this plugin pre-installed (along with two others that also use Composer) over in https://github.com/mykmelez/wordpress-pwa, and the image gets rebuilt by Docker Hub, so unless Docker Hub also sets --prefer-dist as the default, it'll still be handy to set it explicitly.

I've set it explicitly for now, we can revisit later if needed.
